# version: "3"
# services:
#   backend:
#     container_name: backend
#     image: latest/backend
#     restart: always
#     build: ./backend
#     depends_on:
#       - mongo
#     ports:
#       - "8080:8080"
#   mongo:
#     image: mongo:4.0-xenial
#     ports:
#       - "27017:27017"
#     volumes:
#       - notes:/data/db

# volumes:
#   notes:

version: "3"
services:
  backend:
    restart: always
    build: ./backend
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
