version: "3"
services:
  backend:
    networks:
      - webappnetwork
    restart: always
    build: ./backend
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    networks:
      - webappnetwork
    ports:
      - "27017:27017"
  frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend
    ports:
      - "8080:3000"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
